fos_rest:
    disable_csrf_role: false

    format_listener:
        rules:
            - { path: '^/admin', priorities: [ json ], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }
    param_fetcher_listener: true

    unauthorized_challenge: "Basic realm=\"Restricted Area\""
    access_denied_listener:
        json: true

    routing_loader:
        default_format: json
        include_format: false

    view:
        formats:
            json: true
        view_response_listener: true

    body_listener:
        decoders:
            json: fos_rest.decoder.jsontoform
