nelmio_api_doc:
    documentation:
        info:
            title: ShopAPI
            description: Demo project of API for Online shopping portal
            version: 1.0.0
        securityDefinitions:
            token:
                type: apiKey
                description: The token you got on login action with prefix 'Bearer '
                name: Authorization
                in: header
            basic:
                type: basic
        security:
            - token: []
        consumes:
            - application/json
#            - application/x-www-form-urlencoded
#            - multipart/form-data
        produces:
            - application/json
        parameters:
            Locale:
                in: header
                name: Accept-Language
                type: string
                description: Locale
        definitions:
          Error:
            type: object
            required: [code, message]
            properties:
            code:
              type: integer
            message:
              type: string
          FormError:
              allOf:
                  - $ref: '#definitions/Error'
                  - type: object
                    required: [errors]
                    properties:
                        errors:
                            type: object
                            required: [children]
                            properties:
                                errors:
                                    type: array
                                    items:
                                        type: string
                                children:
                                    type: object
                                    description: An array of errors per form field
          Login:
            ref: '#definitions/Login'
            type: object
            required: [username, password]
            properties:
              username:
                type: string
              password:
                type: string
          Token:
            type: object
            required: [token]
            properties:
              token: { type: string }
    areas:
        default:
            path_patterns: [^/customer ]
        admin:
            path_patterns: [ ^/admin ]

